routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('login');
});

//Auth::routes();

/* Authentication Routes */
Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::post('logout', 'Auth\LoginController@logout')->name('logout');

/* Password Reset Routes */
Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::post('password/reset', 'Auth\ResetPasswordController@reset');

/* Registration Routes
Route::get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
Route::post('register', 'Auth\RegisterController@register');
*/

Route::group(['namespace' => 'Control', 'middleware' => ['auth']], function ()
{
    Route::get('/home', 'HomeController@index')->name('home');
    Route::get('users/user', 'UserController@user');
    Route::resource('users', 'UserController');
    Route::resource('user-roles', 'UserRoleController');
    Route::resource('user-statuses', 'UserStatusController');
    Route::resource('schedules', 'ScheduleController');
    Route::resource('events', 'EventController');
    Route::resource('clients', 'ClientController');
    Route::resource('services', 'ServiceController');
    Route::resource('service-categories', 'ServiceCategoryController');
    Route::resource('stories', 'StoryTypeController');
});

/*
DB::listen(function($query) {
    var_dump($query->sql, $query->bindings);
});
*/

resources/views/layouts/auth.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="shortcut icon" type="image/png" href="{{ asset('favicon.png') }}"/>
    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'ServiceNow') }}</title>


    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
    <link rel="stylesheet" href="/css/auth.css">

</head>
<body>

    <div id="app">
        <!-- Content section -->
        <main>
            @yield('content')
        </main>
        <!-- End Content section -->
    </div>

</body>
</html>

resources/views/layouts/control.blade.php
@include('layouts.header')

<div class="layout">
{{--
    <div class="layout-nav">
        <!-- <a class="brand" href="{{ url('/') }}">
            <img src="{{ asset('assets/img/brand.svg') }}" alt="{{ config('app.name', 'Laravel') }}">
        </a> -->
        
        <!-- Layout profile -->
        <div class="layout-profile">
            <div class="photo">
                <i class="fas fa-camera"></i>
                <!-- <img src="" alt=""> -->
            </div>
            <div class="role"></div>
            <div class="email"></div>
        </div>
        <!--/ Layout profile -->

        <div class="sidenav-divider"></div>

        <!-- Layout navigation -->
        <nav class="nav flex-column">
            <a class="nav-link active" href="#">@lang('Schedule')</a>
            <a class="nav-link" href="#">@lang('Clients')</a>
            <a class="nav-link" href="#">@lang('Users')</a>
            <a class="nav-link" href="#">@lang('Statuses')</a>
            <a class="nav-link" href="#">@lang('Roles')</a>
            <a class="nav-link" href="#">@lang('Services')</a>
            <a class="nav-link" href="#">@lang('Categories')</a>
            <a class="nav-link" href="#">@lang('Sessions')</a>
        </nav>
        <!--/ Layout navigation -->

    </div>
--}}
    <!-- Layout navigation -->
    <!-- <div class="layout-nav">
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
            <a class="navbar-brand" href="{{ url('/') }}">{{ config('app.name', 'Laravel') }}</a>

            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="#">@lang('Schedule')</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ route('clients.index') }}">@lang('Clients')</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="usersDropDown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            @lang('Users')
                        </a>
                        <div class="dropdown-menu" aria-labelledby="usersDropDown">
                            <a class="dropdown-item" href="{{ route('users.index') }}">@lang('Users')</a>
                            <a class="dropdown-item" href="{{ route('user-statuses.index') }}">@lang('Statuses')</a>
                            <a class="dropdown-item" href="{{ route('user-roles.index') }}">@lang('Roles')</a>
                        </div>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="servicesDropDown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            @lang('Services')
                        </a>
                        <div class="dropdown-menu" aria-labelledby="servicesDropDown">
                            <a class="dropdown-item" href="{{ route('services.index') }}">@lang('Services')</a>
                            <a class="dropdown-item" href="{{ route('service-categories.index') }}">@lang('Categories')</a>
                        </div>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">@lang('Sessions')</a>
                    </li>
                </ul>
                <div class="ml-auto">
                    <button type="button" class="btn btn-outline-secondary" href="{{ route('logout') }}" onclick="event.preventDefault(); document.getElementById('logout-form').submit();">@lang('Logout')</button>
                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                        @csrf
                    </form>
                </div>
            </div>

        </nav>
    </div> -->
    <!-- / Layout navigation -->



    @if (session('status'))
    <div class="alert alert-success" role="alert">
        {{ session('status') }}
    </div>
    @endif

    <!-- Layout content -->
    <div class="layout-content">
        @yield('content')
    </div>
    <!-- Layout content -->

</div>

@include('layouts.footer')

resources/views/layouts/footer.blade.php
<script>
    function toogleMenu(){
        document.getElementById('main-menu').classList.toggle('open');
        document.getElementById('toggle-main-menu-btn').classList.toggle('is-active');
    }
    document.getElementById('toggle-main-menu-btn').addEventListener('click',function(){
        toogleMenu();
    },false);
</script>

<script src="https://code.jquery.com/jquery-3.3.1.js" integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60=" crossorigin="anonymous"></script>

@stack('scripts')
</body>
</html>

resources/views/layouts/header.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <title>{{ config('app.name', 'ServiceNow') }} - @yield('title')</title>

    <script type="text/javascript">
        const safeData = {
            'csrf_token' : '{{ csrf_token() }}',
            'api_token' : '@if (auth()->check()){{ auth()->user()->api_token }}@endif'
        }
    </script>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">

    @stack('css')

    <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">

    <link rel="stylesheet" href="{{ asset('css/style.css') }}">
    <link rel="stylesheet" href="{{ asset('css/hamburger.css') }}">
</head>
<body>

@include('layouts/menu')

resources/views/layouts/menu.blade.php
<div class="main-menu" id="main-menu">
    <div class="hamburger hamburger--slider" id="toggle-main-menu-btn">
        <div class="hamburger-box">
            <div class="hamburger-inner"></div>
        </div>
    </div>
    <div class="m-body">
        <aside>
            <div class="m-header">
                <a class="logo" href="{{ route('home') }}">
                    <img src="{{ asset('img/menu-logo.png') }}" alt="logotype">
                </a>
                <span class="name">{{ auth()->user()->name }}</span>
                <span class="position">{{ auth()->user()->position }}</span>
            </div>
            <ul>
                <li @if (url()->current() == route('home'))class="active"@endif><a href="{{ route('home') }}">Календарь</a></li>
                <li @if (url()->current() == route('users.index'))class="active"@endif><a href="{{ route('users.index') }}">Сотрудники</a></li>
                <li @if (url()->current() == route('schedules.index'))class="active"@endif><a href="{{ route('schedules.index') }}">Расписания</a></li>
                <li @if (url()->current() == route('services.index'))class="active"@endif><a href="{{ route('services.index') }}">Услуги</a></li>
                <li @if (url()->current() == route('clients.index'))class="active"@endif><a href="{{ route('clients.index') }}">Клиенты</a></li>

                <li class="nav-item logout-link">
                    <a href="{{ route('logout') }}" class="nav-link disabled" onclick="event.preventDefault(); document.getElementById('logout-form').submit();" title="{{ trans('auth/login.logout') }}">
                        Выход
                    </a>
                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                        {{ csrf_field() }}
                    </form>
                </li>
            </ul>
            <div class="m-footer">
                <span class="copyright">&copy; Service Now - 2018</span>
            </div>
        </aside>
    </div>
</div>

<style>
    .main-menu {
        position: absolute;
        width: 40px;
        height: 40px;
        background-color: #fff;
        z-index: 10;
    }
    .main-menu .m-body {
        position: absolute;
        left: 0;
        top: 0;
        width: 100%;
        height: 100%;
        transform: scaleX(0);
        opacity: 0;
        transition: all .3s;
        display:inline-block;
        transform-origin:left;
        z-index: -1;
    }
    .main-menu aside {
        width: 400px;
        height: 100%;
        position: absolute;
        top: 0;
        left: 0;
        background-color: #fff;
    }
    .main-menu.open {
        width: 100%;
        height: 100%;
        background-color: rgba(110, 110, 110, 0.29);
    }
    .main-menu.open .m-body {
        transform: scaleX(1);
        opacity: 1;
        transition: all .3s;
        transform-origin:left;
    }
    /**************************header*************************/
    .main-menu aside .m-header {
        padding: 0 15px 15px 15px;
    }
    .main-menu aside .m-header a {
        display: inline-block;
        width: 200px;
        height: auto;
        margin-left: 50%;
        transform: translateX(-50%);
        margin-top: 2px;
    }
    .main-menu aside .m-header a img {
        width: 100%;
        height: 100%;
    }
    .main-menu aside .m-header .name {
        display: block;
        color: #333;
        padding: 3px 0;
        margin-top: 10px;
    }
    .main-menu aside .m-header .position {
        display: block;
        color: #999;
    }
    /*********************************************************/
    /****************************menu*************************/
    .main-menu aside ul {
        margin: 0;
        padding: 0;
        list-style: none;
    }
    .main-menu aside ul li {
        height: 60px;
        line-height: 60px;
        padding: 0 10px;
        transition: all .3s linear;
        background-color: #fff;
    }
    .main-menu aside ul li a {
        text-decoration: none;
        color: #646464;
        font-size: 22px;
        display: block;
        width: 100%;
        height: 60px;
        line-height: 60px;
        padding: 0 15px;
    }
    .main-menu aside ul li:hover {
        background-color: rgba(75, 116, 255, 0.81);
        transition: all .3s linear;
    }
    .main-menu aside ul li:hover a{
        color: #fff;
        transition: all .3s linear;
    }
    .main-menu aside ul li.active {
        background-color: #4b74ff;
    }
    .main-menu aside ul li.active a {
        color: #fff;
    }
    /*********************************************************/
    /**************************footer*************************/
    .main-menu aside .m-footer {
        position: absolute;
        width: 100%;
        padding: 15px;
        text-align: center;
        left: 0;
        bottom: 0;
    }
    .main-menu aside .m-footer .copyright {
        color: #d6d6d6;
    }
</style>

resources/views/layouts/sidebar.blade.php
<div>
    @auth
        <duv>
            @if (Auth::user()->image != '')
                <img src="{{ Auth::user()->image }}" alt="{{ Auth::user()->name }}" />
            @endif
                <p>{{ Auth::user()->name }}</p>
                <p><a href="mailto:{{ Auth::user()->email }}">{{ Auth::user()->email }}</a></p>
        </duv>
    @endauth

    <div>
        <ul>
            <li><a href="{{ route('home') }}">@lang('Home')</a></li>
            <li>
                <a href="{{ route('users.index') }}">@lang('Users')</a>
                <ul>
                    <li><a href="{{ route('user-statuses.index') }}">@lang('Statuses')</a></li>
                    <li><a href="{{ route('user-roles.index') }}">@lang('Roles')</a></li>
                </ul>
            </li>
            <li>
                <a href="{{ route('services.index') }}">@lang('Services')</a>
                <ul>
                    <li><a href="{{ route('service-categories.index') }}">@lang('Categories')</a></li>
                </ul>
            </li>
            <li><a href="{{ route('clients.index') }}">@lang('Clients')</a></li>
            <li><a href="#">@lang('Schedule')</a></li>
            <li><a href="#">@lang('Agenda')</a></li>
            <li><a href="#">@lang('Activity')</a></li>
            <li><a href="#">@lang('Settings')</a></li>
        </ul>
    </div>
    
</div>